### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by wun-yu-lin**
Hi, I am wun-yu lin aka 林文昱
Week4 task finish, please review

http://13.210.24.111:3000/ 
http://13.210.24.111:3000/attraction/1

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Show error message if we try to sign in with wrong email and password.
2. Your input validation procedure dose not work properly. Always submit form and refresh page in any situation.

**Comment by wun-yu-lin** [comment]
Hi, I am wun-yu lin aka 林文昱
Week4 issue fix, please review

1. when sign in with wrong, show error message
2. Only successfully login/signup, refresh page

http://13.210.24.111:3000/
http://13.210.24.111:3000/attraction/1

**Review by cwpeng — CHANGES_REQUESTED** [review]
When I sign up with password only 3 characters, your UI shows it requires at least 8 characters. But at the same time, it works and sign up successfully.

**Comment by wun-yu-lin** [comment]
Hi, I am wun-yu lin aka 林文昱
Week4 issue fix, please review

1. fix the front-end program, a issue about user input filter rule will skip the by form, add ```document.querySelector("#signin_form").checkValidity()``` to fix this issue
2. Modify back-end program, optimize user API, using HTTPstatus code enum

http://13.210.24.111:3000/
http://13.210.24.111:3000/attraction/1

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
