### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by wun-yu-lin**
Hi, 
I am wun-yu lin (林文昱)
Finish week2 Task 2-1 to 2-5, please review, TKS!!!
test url:
http://13.210.24.111:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your code will load the same page multiple times if we scroll down and up quickly.
2. Border of attraction block should be only 1px.
3. It's much better to use proportional width for attraction blocks in small to middle size devices.

未命名-6

**Comment by wun-yu-lin** [comment]
1. using IntersectionObserver object, prevent load same page multiple times.
2. attraction box 1px
3. using proportional width for attraction blocks
Test URL : http://13.210.24.111:3000/
林文昱
image

**Comment by wun-yu-lin** [comment]
Please review, TKS!!

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Still, load the same page multiple times.
2. Border are still 2px. We check the final result, not just single CSS setting. Try to make a simple test to see what 1px should look like.
3. Layout exceeds screen width in some sizes of devices.


https://github.com/wun-yu-lin/WeHelp_second_stage_project/assets/6104683/a87edf17-ba91-42fd-8dd8-273505f3acfc

**Comment by wun-yu-lin** [comment]
HI, 
I am wun-yu lin (林文昱)
Finish issue, please review
test URL
http://13.210.24.111:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
